FROM python:3.12-slim-bookworm

WORKDIR /frontend

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8501

ENTRYPOINT ["streamlit","run"]

CMD ["streamlit_app.py"]